// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RadminResources.cs" with this contents:
/*
namespace AppCode.Extensions.Radmin.Data
{
  public partial class RadminResources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Ext Radmin/
// User:        2sic Web-Developer
namespace AppCode.Extensions.Radmin.Data
{
  // This is a generated class for RadminResources (scope: Extensions.Radmin)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RadminResources data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.SearchLabel`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope Extensions.Radmin.
  /// </remarks>
  public partial class RadminResources: AutoGenerated.ZAutoGenRadminResources
  {  }
}

namespace AppCode.Extensions.Radmin.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RadminResources' in scope 'Extensions.Radmin'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRadminResources: Custom.Data.CustomItem
  {
    /// <summary>
    /// SearchLabel as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SearchLabel", scrubHtml: true) etc.
    /// </summary>
    public string SearchLabel => _item.String("SearchLabel", fallback: "");

    /// <summary>
    /// ViewConfigModeLabel as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ViewConfigModeLabel", scrubHtml: true) etc.
    /// </summary>
    public string ViewConfigModeLabel => _item.String("ViewConfigModeLabel", fallback: "");
  }
}