// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RadminTableColumn.cs" with this contents:
/*
namespace AppCode.Extensions.Radmin.Data
{
  public partial class RadminTableColumn
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: App Ext Radmin/
// User:        2sic Web-Developer
namespace AppCode.Extensions.Radmin.Data
{
  // This is a generated class for RadminTableColumn (scope: Extensions.Radmin)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RadminTableColumn data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.HorizontalAlignment`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope Extensions.Radmin.
  /// </remarks>
  public partial class RadminTableColumn: AutoGenerated.ZAutoGenRadminTableColumn
  {  }
}

namespace AppCode.Extensions.Radmin.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RadminTableColumn' in scope 'Extensions.Radmin'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRadminTableColumn: Custom.Data.CustomItem
  {
    /// <summary>
    /// HorizontalAlignment as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HorizontalAlignment", scrubHtml: true) etc.
    /// </summary>
    public string HorizontalAlignment => _item.String("HorizontalAlignment", fallback: "");

    /// <summary>
    /// LinkEnable as bool. <br/>
    /// To get nullable use .Get("LinkEnable") as bool?;
    /// </summary>
    public bool LinkEnable => _item.Bool("LinkEnable");

    /// <summary>
    /// LinkParameters as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LinkParameters", scrubHtml: true) etc.
    /// </summary>
    public string LinkParameters => _item.String("LinkParameters", fallback: "");

    /// <summary>
    /// LinkViewId as single item of RadminDetails.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type RadminDetails was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public RadminDetails LinkViewId => _linkViewId ??= _item.Child<RadminDetails>("LinkViewId");
    private RadminDetails _linkViewId;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// TooltipEnabled as bool. <br/>
    /// To get nullable use .Get("TooltipEnabled") as bool?;
    /// </summary>
    public bool TooltipEnabled => _item.Bool("TooltipEnabled");

    /// <summary>
    /// TooltipSelector as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TooltipSelector", scrubHtml: true) etc.
    /// </summary>
    public string TooltipSelector => _item.String("TooltipSelector", fallback: "");

    /// <summary>
    /// ValueFormat as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ValueFormat", scrubHtml: true) etc.
    /// </summary>
    public string ValueFormat => _item.String("ValueFormat", fallback: "");

    /// <summary>
    /// ValueSelector as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ValueSelector", scrubHtml: true) etc.
    /// </summary>
    public string ValueSelector => _item.String("ValueSelector", fallback: "");

    /// <summary>
    /// Width as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Width", scrubHtml: true) etc.
    /// </summary>
    public string Width => _item.String("Width", fallback: "");
  }
}