// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "DataViewTableConfig.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class DataViewTableConfig
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: 2sxc-Tables/
// User:        SuperUser Account
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for DataViewTableConfig 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// DataViewTableConfig data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.ActiveColumnToolbars`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class DataViewTableConfig: AutoGenerated.ZAutoGenDataViewTableConfig
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.DataViewTableConfig in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenDataViewTableConfig: Custom.Data.CustomItem
  {
    /// <summary>
    /// ActiveColumnToolbars as bool. <br/>
    /// To get nullable use .Get("ActiveColumnToolbars") as bool?;
    /// </summary>
    public bool ActiveColumnToolbars => _item.Bool("ActiveColumnToolbars");

    /// <summary>
    /// ColumnsAutoShowRemaining as bool. <br/>
    /// To get nullable use .Get("ColumnsAutoShowRemaining") as bool?;
    /// </summary>
    public bool ColumnsAutoShowRemaining => _item.Bool("ColumnsAutoShowRemaining");

    /// <summary>
    /// DataContentType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DataContentType", scrubHtml: true) etc.
    /// </summary>
    public string DataContentType => _item.String("DataContentType", fallback: "");

    /// <summary>
    /// DataQuery as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DataQuery", scrubHtml: true) etc.
    /// </summary>
    public string DataQuery => _item.String("DataQuery", fallback: "");

    /// <summary>
    /// DataViewColumnConfig as list of DataViewColumnConfig.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type DataViewColumnConfig was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<DataViewColumnConfig> DataViewColumnConfig => _dataViewColumnConfig ??= _item.Children<DataViewColumnConfig>("DataViewColumnConfig");
    private IEnumerable<DataViewColumnConfig> _dataViewColumnConfig;

    /// <summary>
    /// PagingMode as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("PagingMode", scrubHtml: true) etc.
    /// </summary>
    public string PagingMode => _item.String("PagingMode", fallback: "");

    /// <summary>
    /// PagingSize as int. <br/>
    /// To get other types use methods such as .Decimal("PagingSize")
    /// </summary>
    public int PagingSize => _item.Int("PagingSize");

    /// <summary>
    /// Search as bool. <br/>
    /// To get nullable use .Get("Search") as bool?;
    /// </summary>
    public bool Search => _item.Bool("Search");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// ViewId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ViewId", scrubHtml: true) etc.
    /// </summary>
    public string ViewId => _item.String("ViewId", fallback: "");
  }
}