// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RadminDetails.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class RadminDetails
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: Extension Radmin/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for RadminDetails 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RadminDetails data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.DataContentType`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class RadminDetails: AutoGenerated.ZAutoGenRadminDetails
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RadminDetails' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRadminDetails: Custom.Data.CustomItem
  {
    /// <summary>
    /// DataContentType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DataContentType", scrubHtml: true) etc.
    /// </summary>
    public string DataContentType => _item.String("DataContentType", fallback: "");

    /// <summary>
    /// ViewId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ViewId", scrubHtml: true) etc.
    /// </summary>
    public string ViewId => _item.String("ViewId", fallback: "");
  }
}